export declare type Cid = { '/': string };

export const TYPES = {
  ApiServer: Symbol('ApiServer'),
  AirtableClient: Symbol('AirtableClient'),
  AirtableClientConfig: Symbol('AirtableClientConfig'),
  CommandBus: Symbol('CommandBus'),
  CommandHandler: Symbol('CommandHandler'),
  DatacapAllocatorEventStore: Symbol('DatacapAllocatorEventStore'),
  DatacapAllocatorRepository: Symbol('DatacapAllocatorRepository'),
  Db: Symbol('Db'),
  Event: Symbol('Event'),
  EventBus: Symbol('EventBus'),
  GithubClient: Symbol('GithubClient'),
  GithubClientConfig: Symbol('GithubClientConfig'),
  Logger: Symbol('Logger'),
  LotusClient: Symbol('LotusClient'),
  LotusClientConfig: Symbol('LotusClientConfig'),
  QueryBus: Symbol('QueryBus'),
  QueryHandler: Symbol('QueryHandler'),
  RabbitMQConfig: Symbol('RabbitMQConfig'),
  MessageService: Symbol('MessageService'),
  PullRequestService: Symbol('PullRequestService'),
  RoleService: Symbol('RoleService'),
  ApplicationDetailsRepository: Symbol('ApplicationDetailsRepository'),
  IssueDetailsRepository: Symbol('IssueDetailsRepository'),
  IssueMapper: Symbol('IssueMapper'),
  RpcProvider: Symbol('RpcProvider'),
  RpcProviderConfig: Symbol('RpcProviderConfig'),
  DataCapMapper: Symbol('DataCapMapper'),
  MetaAllocatorService: Symbol('MetaAllocatorService'),
  MetaAllocatorRepository: Symbol('MetaAllocatorRepository'),
  RkhConfig: Symbol('RkhConfig'),
  AllocationPathResolver: Symbol('AllocationPathResolver'),
  RefreshAuditPublisher: Symbol('RefreshAuditPublisher'),
  RefreshAuditService: Symbol('RefreshAuditService'),
  AllocatorRegistryConfig: Symbol('AllocatorRegistryConfig'),
  AllocatorGovernanceConfig: Symbol('AllocatorGovernanceConfig'),
  AuditMapper: Symbol('AuditMapper'),
  AuditsChangesEventStore: Symbol('AuditsChangesEventStore'),
  AuditOutcomeResolver: Symbol('AuditOutcomeResolver'),
  UpsertIssueStrategyResolver: Symbol('UpsertIssueStrategyResolver'),
  GovernanceConfig: Symbol('GovernanceConfig'),
  MetaAllocatorConfig: Symbol('MetaAllocatorConfig'),
};

export type ConfigTypes = typeof TYPES;
